name: ci-go

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  go-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: "v1.20"

      - name: Build
        run: make

